import { CategoryItem, ProductItem, ProductVariantItem, OrderItem, CouponItem, StoreSettingsItem } from "@/types";

export function buildProductVariants(
  productId: number,
  sku: string,
  sizes: string[],
  colors: { name: string; hex: string; imageUrl?: string }[],
  basePrice?: number
): ProductVariantItem[] {
  let varId = productId * 100;
  const variants: ProductVariantItem[] = [];
  for (const s of sizes) {
    for (const c of colors) {
      varId++;
      const cleanColor = c.name.trim().replace(/\s+/g, "");
      variants.push({
        id: varId,
        productId,
        size: s,
        colorName: c.name,
        colorHex: c.hex,
        sku: `${sku || "SKU"}-${s}-${cleanColor}`,
        stock: 5,
        price: basePrice || null,
        imageUrl: c.imageUrl || null,
      });
    }
  }
  return variants;
}

export const INITIAL_CATEGORIES: CategoryItem[] = [
  {
    id: 1,
    name: "أوفر سايز وتي شيرتات",
    slug: "oversized-tshirts",
    image: "https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=800&auto=format&fit=crop&q=80",
    description: "تيشيرتات قطن مصري 100% بقصات عصرية مريحة تناسب جميع الإطلالات الكاجوال",
    displayOrder: 1,
    productsCount: 6,
  },
  {
    id: 2,
    name: "هوديز وسويت شيرت",
    slug: "hoodies-sweatshirts",
    image: "https://images.unsplash.com/photo-1556905055-8f358a7a47b2?w=800&auto=format&fit=crop&q=80",
    description: "ميلتون قطني ثقيل معالج ومبطن بفرو ناعم للدفء والأناقة في شتاء مصر",
    displayOrder: 2,
    productsCount: 5,
  },
  {
    id: 3,
    name: "قمصان كاجوال وكتان",
    slug: "casual-shirts",
    image: "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=800&auto=format&fit=crop&q=80",
    description: "قمصان كتان طبيعي وقطن بيزك تناسب العمل والخروجات الصيفية",
    displayOrder: 3,
    productsCount: 4,
  },
  {
    id: 4,
    name: "بناطيل وسويت بانتس",
    slug: "pants-sweatpants",
    image: "https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=800&auto=format&fit=crop&q=80",
    description: "بناطيل كارجو وجينز مريح وسويت بانتس قطني بأعلى خامات التحمل",
    displayOrder: 4,
    productsCount: 4,
  },
  {
    id: 5,
    name: "ملابس نسائية وكاجوال",
    slug: "women-collection",
    image: "https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=800&auto=format&fit=crop&q=80",
    description: "أطقم دريسات كاجوال، عبايات عصرية، وبليزرات بتصاميم راقية ومحتشمة",
    displayOrder: 5,
    productsCount: 5,
  },
  {
    id: 6,
    name: "بليزرات وجواكت شياكة",
    slug: "blazers-jackets",
    image: "https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=800&auto=format&fit=crop&q=80",
    description: "بليزرات وجواكت وتر بروف وبومبر جاكيت للمناسبات والإطلالات الرسمية",
    displayOrder: 6,
    productsCount: 3,
  },
  {
    id: 7,
    name: "حقائب وشنط يد",
    slug: "bags",
    image: "https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=800&auto=format&fit=crop&q=80",
    description: "شنط يد جلدية فاخرة وحقائب كروس عصرية بتصاميم أنيقة وعملية لجميع المناسبات",
    displayOrder: 7,
    productsCount: 1,
  },
  {
    id: 8,
    name: "توك وإكسسوارات شعر",
    slug: "hair-clips",
    image: "https://res.cloudinary.com/dnhydbrvc/image/upload/f_auto,q_auto/modanil_hairclips/modanil_hairclips_01.jpg",
    description: "مساكات وتوك شعر ستان حريري كورية وإكسسوارات شعر ناعمة لتسريحات يومية جذابة",
    displayOrder: 8,
    productsCount: 16,
  },
];

const RAW_INITIAL_PRODUCTS: ProductItem[] = [
  {
    id: 101,
    name: "تيشيرت أوفر سايز بيزك - قطن مصري فاخر",
    slug: "oversize-basic-tshirt",
    description: "تيشيرت بقصة أوفر سايز عصرية، مصنوع من أجود أنواع خيوط القطن المصري طويل التيلة 100% معالج ضد الانكماش وتغير اللون. مريح للغاية في فصل الصيف ويمتاز بياقة متماسكة لا تتمدد مع الغسيل المتكرر.",
    fabricDetails: "قطن مصري 100% - وزن 240 جرام/م² - تقفيل خياطة مزدوجة",
    price: 490,
    salePrice: 380,
    stock: 25,
    categoryId: 1,
    categoryName: "أوفر سايز وتي شيرتات",
    sizes: ["S", "M", "L", "XL", "2XL"],
    colors: [
      { name: "أسود ملكي", hex: "#111827" },
      { name: "أوف وايت", hex: "#f3f4f6" },
      { name: "زيتي زتونى", hex: "#3f4f38" },
      { name: "رمادي ميلانج", hex: "#6b7280" },
    ],
    images: [
      "https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1618354691373-d851c5c3a990?w=800&auto=format&fit=crop&q=80",
    ],
    isFeatured: true,
    isNew: true,
    sku: "TSH-OVR-01",
  },
  {
    id: 102,
    name: "هودي ميلتون ثقيل مبطن كابيشو - كايرو إديشن",
    slug: "cairo-heavy-hoodie",
    description: "هودي شتوي فائق الدفء بخامة قطن ميلتون مصري 3 خيوط سميكة، جيب كنغر أمامي واسع مع كابيشو مبطن برباط سميك متين. أساور مرنة مريحة.",
    fabricDetails: "ميلتون قطني 85% مع 15% بوليستر مانع للوبرة - وزن 380 جرام",
    price: 850,
    salePrice: 690,
    stock: 14,
    categoryId: 2,
    categoryName: "هوديز وسويت شيرت",
    sizes: ["M", "L", "XL", "2XL", "3XL"],
    colors: [
      { name: "كحلي داكن", hex: "#1e293b" },
      { name: "بيج رملي", hex: "#d7c4a9" },
      { name: "عنابي مارون", hex: "#5b1924" },
    ],
    images: [
      "https://images.unsplash.com/photo-1556905055-8f358a7a47b2?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1509967419530-da38b4704bc6?w=800&auto=format&fit=crop&q=80",
    ],
    isFeatured: true,
    isNew: true,
    sku: "HOD-MIL-02",
  },
  {
    id: 103,
    name: "قميص كتان طبيعي صيفي خفيف",
    slug: "natural-linen-summer-shirt",
    description: "قميص صيفي مصنوع من الكتان والقطن الطبيعي عالي التهوية بياقة ماو (ماندرين) عصرية بدون ربطة عنق، مناسب لأجواء الساحل والصيف في مصر.",
    fabricDetails: "كتان طبيعي 70% + قطن 30% معالج لمقاومة الكرمشة الشديدة",
    price: 680,
    salePrice: 520,
    stock: 18,
    categoryId: 3,
    categoryName: "قمصان كاجوال وكتان",
    sizes: ["M", "L", "XL", "2XL"],
    colors: [
      { name: "أبيض صيفي", hex: "#ffffff" },
      { name: "أزرق سماوي", hex: "#93c5fd" },
      { name: "بيج ترابي", hex: "#caba9c" },
    ],
    images: [
      "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=800&auto=format&fit=crop&q=80",
    ],
    isFeatured: true,
    isNew: false,
    sku: "SHT-LIN-03",
  },
  {
    id: 104,
    name: "بنطلون كارجو عملي بجيوب جانبية متعددة",
    slug: "tactical-cargo-pants",
    description: "بنطلون كارجو بـ 6 جيوب عملية واسعة ومحكمة، قصة ريلكسد مريحة للحركة اليومية، نسيج جبردين مصري قطني متين يتحمل الغسيل والاستخدام الشاق.",
    fabricDetails: "جبردين قطن مصري 100% مع خياطة تريبل مقواة",
    price: 620,
    salePrice: 490,
    stock: 20,
    categoryId: 4,
    categoryName: "بناطيل وسويت بانتس",
    sizes: ["30", "32", "34", "36", "38"],
    colors: [
      { name: "زيتي عسكري", hex: "#4b5320" },
      { name: "أسود فحمي", hex: "#1f2937" },
      { name: "كاكي صحراوي", hex: "#c3b091" },
    ],
    images: [
      "https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=800&auto=format&fit=crop&q=80",
    ],
    isFeatured: false,
    isNew: true,
    sku: "PNT-CRG-04",
  },
  {
    id: 105,
    name: "دريس كاجوال طويل بحزام خصر - ناعم ومريح",
    slug: "casual-cotton-long-dress",
    description: "فستان نسائي كاجوال طويل ومحتشم بخامة بوبلين قطن خفيفة وباردة على الجسم، مع أكمام قابلة للثني وحزام خصر متناسق يمنح مظهراً راقياً ومريحاً للخروج النهاري.",
    fabricDetails: "قطن بوبلين ناعم 100% لا يشف ومقاوم لحرارة الصيف",
    price: 950,
    salePrice: 750,
    stock: 12,
    categoryId: 5,
    categoryName: "ملابس نسائية وكاجوال",
    sizes: ["S", "M", "L", "XL", "2XL"],
    colors: [
      { name: "أخضر زمردي", hex: "#065f46" },
      { name: "وردي ناعم", hex: "#f472b6" },
      { name: "أزرق نيلي", hex: "#1e3a8a" },
    ],
    images: [
      "https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?w=800&auto=format&fit=crop&q=80",
    ],
    isFeatured: true,
    isNew: true,
    sku: "DRS-WMS-05",
  },
  {
    id: 106,
    name: "بليزر كاجوال إيطالي سليم فيت",
    slug: "casual-slim-fit-blazer",
    description: "بليزر كاجوال عصري يمكن ارتداؤه فوق تيشيرت أو قميص، تفصيل إيطالي مبطن جزئياً ليمنحك خفة الحركة والأناقة في المقابلات والمناسبات والعمل.",
    fabricDetails: "مزيج قطن ولكرا خفيف يمنح مرونة وأناقة فائقة",
    price: 1350,
    salePrice: 1090,
    stock: 9,
    categoryId: 6,
    categoryName: "بليزرات وجواكت شياكة",
    sizes: ["48", "50", "52", "54", "56"],
    colors: [
      { name: "كحلي رويال", hex: "#1e3a8a" },
      { name: "رمادي غامق", hex: "#374151" },
      { name: "هافان جملي", hex: "#92400e" },
    ],
    images: [
      "https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=800&auto=format&fit=crop&q=80",
    ],
    isFeatured: true,
    isNew: false,
    sku: "BLZ-SLM-06",
  },
  {
    id: 107,
    name: "سويت بانتس قطني مريح بجيوب سوستة",
    slug: "comfort-cotton-sweatpants",
    description: "سويت بانتس مريح برباط خصر مطاطي متين وجيوب جانبية مزودة بسوستة لحفظ الهاتف والمحفظة بأمان أثناء الحركة وممارسة الرياضة أو المشاوير اليومية.",
    fabricDetails: "قطن ميلتون مصري مطاطي 95% قطن 5% ليكرا",
    price: 490,
    salePrice: 390,
    stock: 30,
    categoryId: 4,
    categoryName: "بناطيل وسويت بانتس",
    sizes: ["M", "L", "XL", "2XL"],
    colors: [
      { name: "أسود", hex: "#111827" },
      { name: "رمادي ميلانج", hex: "#6b7280" },
      { name: "أزرق كحلي", hex: "#1e293b" },
    ],
    images: [
      "https://images.unsplash.com/photo-1552902865-b72c031ac5ea?w=800&auto=format&fit=crop&q=80",
    ],
    isFeatured: false,
    isNew: true,
    sku: "PNT-SWT-07",
  },
  {
    id: 108,
    name: "سويت شيرت كرو نك مطبوع - ديزاين عربي أصيل",
    slug: "crewneck-arabic-typography-sweatshirt",
    description: "سويت شيرت رقبة دائرية كرو نك بطباعة حرارية عالية الدقة لعبارات وخطوط عربية أصيلة تدوم طويلاً دون تشقق.",
    fabricDetails: "قطن مصري ناعم مبطن دافئ",
    price: 650,
    salePrice: 530,
    stock: 16,
    categoryId: 2,
    categoryName: "هوديز وسويت شيرت",
    sizes: ["S", "M", "L", "XL", "2XL"],
    colors: [
      { name: "أبيض كريمي", hex: "#f9fafb" },
      { name: "أسود مطفي", hex: "#18181b" },
    ],
    images: [
      "https://images.unsplash.com/photo-1578587018452-892bacefd3f2?w=800&auto=format&fit=crop&q=80",
    ],
    isFeatured: false,
    isNew: false,
  },
  {
    id: 109,
    name: "شنطة كروس كلاسيك جلد طبيعي - MODANIL Signature",
    slug: "classic-leather-crossbody-bag",
    description: "شنطة كروس أنيقة وبيد علوية مصنوعة من الجلد الطبيعي الفاخر بتشطيب ناعم وأقفال معدنية باللون الذهبي المطفي المقاوم للصدأ. تتضمن حزام كتف قابل للتعديل وجيب داخلي مبطن بسوستة لحفظ المقتنيات اليومية بأناقة وأمان.",
    fabricDetails: "جلد طبيعي فاخر 100% - بطانة ستان قطني ناعم - إكسسوارات معدنية ذهبية",
    price: 890,
    salePrice: 720,
    stock: 15,
    categoryId: 7,
    categoryName: "حقائب وشنط يد",
    categorySlug: "bags",
    sizes: ["مقاس موحد"],
    colors: [
      { name: "أسود ملكي", hex: "#111827" },
      { name: "هافان جملي", hex: "#92400e" },
      { name: "عنابي مارون", hex: "#5b1924" },
    ],
    images: [
      "https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1590874103328-eac38a683ce7?w=800&auto=format&fit=crop&q=80",
    ],
    isFeatured: true,
    isNew: true,
    sku: "BAG-CRS-09",
    hasSizeGuide: false,
    badgeText: "جلد طبيعي 💼",
  },
  {
    id: 110,
    name: "طقم مساكات وتوك شعر ستان حريري كوري (3 قطع)",
    slug: "korean-silk-hair-clips-set",
    description: "مجموعة أنيقة مكونة من 3 قطع من توك ومساكات الشعر المصنوعة من قماش الستان الحريري اللامع والمصممة خصيصاً لتثبيت الشعر بلطف دون شد أو تقصف. ألوان هادئة كلاسيكية تناسب جميع أوقات اليوم والمناسبات.",
    fabricDetails: "ستان حريري ناعم 100% مع مشبك داخلي مرن ومتين",
    price: 240,
    salePrice: 190,
    stock: 25,
    categoryId: 8,
    categoryName: "توك وإكسسوارات شعر",
    categorySlug: "hair-clips",
    sizes: ["مقاس موحد"],
    colors: [
      { name: "وردي لؤلؤي", hex: "#f472b6" },
      { name: "شامبين ذهبي", hex: "#fde68a" },
      { name: "أسود كلاسيك", hex: "#111827" },
    ],
    images: [
      "https://images.unsplash.com/photo-1606760227091-3dd870d97f1d?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=800&auto=format&fit=crop&q=80",
    ],
    isFeatured: true,
    isNew: true,
    sku: "ACC-CLP-10",
    hasSizeGuide: false,
    badgeText: "إكسسوار حصري ✨",
  },
  {
    id: 111,
    name: "طقم مساكات شعر كريستال الفراشة المضيئة (4 قطع)",
    slug: "modanil-butterfly-crystal-hair-clips-set",
    description: "طقم أنيق مكون من 4 مساكات شعر بتصميم الفراشة الكريستالية الشفافة والملونة من تشكيلة MODANIL. مصنوعة من أكريليك فاخر عالي اللمعان مع مشبك زنبركي معدني قوي ومريح يمنح تسريحتك لمسة أنثوية ناعمة طوال اليوم.",
    fabricDetails: "أكريليك شفاف نقي 100% - مشابك معدنية متينة مقاومة للصدأ",
    price: 195,
    salePrice: 155,
    stock: 20,
    categoryId: 8,
    categoryName: "توك وإكسسوارات شعر",
    categorySlug: "hair-clips",
    sizes: ["مقاس موحد"],
    colors: [
      { name: "وردي كريستال", hex: "#f472b6" },
      { name: "شفاف نقي", hex: "#f8fafc" },
      { name: "أصفر عسلي", hex: "#fde047" },
    ],
    images: [
      "https://res.cloudinary.com/dnhydbrvc/image/upload/f_auto,q_auto/modanil_hairclips/modanil_hairclips_01.jpg",
      "https://res.cloudinary.com/dnhydbrvc/image/upload/f_auto,q_auto/modanil_hairclips/modanil_hairclips_02.jpg",
      "https://res.cloudinary.com/dnhydbrvc/image/upload/f_auto,q_auto/modanil_hairclips/modanil_hairclips_03.jpg",
    ],
    isFeatured: true,
    isNew: true,
    sku: "ACC-CLP-01",
    hasSizeGuide: false,
    badgeText: "إكسسوار حصري ✨",
  },
  {
    id: 112,
    name: "طقم كلبسات شعر فيونكة كلاسيكية ميني (6 قطع)",
    slug: "modanil-ribbon-bow-claw-clips-set",
    description: "مجموعة فاخرة مكونة من 6 كلبسات شعر بتصميم الفيونكة الباريسية الأنيقة من MODANIL. ألوان ناعمة ومحايدة تناسب جميع الإطلالات اليومية والعملية وتثبت خصلات الشعر بأناقة دون شد أو إجهاد.",
    fabricDetails: "راتنج بوليمر ناعم عالي المتانة - سوستة معدنية ذهبية",
    price: 220,
    salePrice: 175,
    stock: 25,
    categoryId: 8,
    categoryName: "توك وإكسسوارات شعر",
    categorySlug: "hair-clips",
    sizes: ["مقاس موحد"],
    colors: [
      { name: "كراميل وبني", hex: "#92400e" },
      { name: "أخضر ميرمية", hex: "#65a30d" },
      { name: "أوف وايت كريمي", hex: "#fef3c7" },
      { name: "عسلي تايجر", hex: "#78350f" },
    ],
    images: [
      "https://res.cloudinary.com/dnhydbrvc/image/upload/f_auto,q_auto/modanil_hairclips/modanil_hairclips_04.jpg",
      "https://res.cloudinary.com/dnhydbrvc/image/upload/f_auto,q_auto/modanil_hairclips/modanil_hairclips_05.jpg",
    ],
    isFeatured: true,
    isNew: true,
    sku: "ACC-CLP-02",
    hasSizeGuide: false,
    badgeText: "إكسسوار حصري ✨",
  },
  {
    id: 113,
    name: "بطاقة كلبسات شعر ميني مطفية الألوان الترابية (18 قطعة)",
    slug: "modanil-matte-mini-claw-clips-card",
    description: "لوحة متكاملة تحتوي على 18 كلبسة شعر صغيرة بتشطيب مطفي ناعم الملمس (Matte Finish) بألوان ترابية كلاسيكية. مثالية لتسريحات الرفع الجزئي وتزيين الضفائر وتثبيت خصلات الشعر الأمامية.",
    fabricDetails: "بلاستيك غير لامع عالي الجودة مع مشابك تثبيت محكمة",
    price: 180,
    salePrice: 140,
    stock: 30,
    categoryId: 8,
    categoryName: "توك وإكسسوارات شعر",
    categorySlug: "hair-clips",
    sizes: ["مقاس موحد"],
    colors: [
      { name: "ألوان ترابية نود", hex: "#78350f" },
      { name: "ألوان الباستيل", hex: "#334155" },
    ],
    images: [
      "https://res.cloudinary.com/dnhydbrvc/image/upload/f_auto,q_auto/modanil_hairclips/modanil_hairclips_06.jpg",
    ],
    isFeatured: false,
    isNew: true,
    sku: "ACC-CLP-03",
    hasSizeGuide: false,
    badgeText: "إكسسوار حصري ✨",
  },
  {
    id: 114,
    name: "عجلة بنس ومساكات شعر تيك تاك سوداء كلاسيك (16 قطعة)",
    slug: "modanil-glossy-snap-hair-clips-wheel",
    description: "طقم كلاسيكي لا غنى عنه مكوّن من 16 بنسة تيك تاك سوداء لامعة بطلاء ناعم مقاوم للتقشر من MODANIL. تثبيت عملي ومريح للشعر اليومي دون أي تشابك.",
    fabricDetails: "معدن كربوني مرن مطلي بطبقة إيبوكسي سوداء لامعة",
    price: 150,
    salePrice: 120,
    stock: 35,
    categoryId: 8,
    categoryName: "توك وإكسسوارات شعر",
    categorySlug: "hair-clips",
    sizes: ["مقاس موحد"],
    colors: [
      { name: "أسود لامع ملكي", hex: "#111827" },
    ],
    images: [
      "https://res.cloudinary.com/dnhydbrvc/image/upload/f_auto,q_auto/modanil_hairclips/modanil_hairclips_07.jpg",
    ],
    isFeatured: false,
    isNew: false,
    sku: "ACC-CLP-04",
    hasSizeGuide: false,
    badgeText: "إكسسوار حصري ✨",
  },
  {
    id: 115,
    name: "مجموعة كلبسات الشعر الفرنسية المقوسة اللامعة",
    slug: "modanil-french-arch-claw-clips-collection",
    description: "كلبسات شعر فاخرة بتصميم فرنسي مقوّس وتدرجات ألوان راقية تعكس الفخامة. تناسب الشعر الكثيف والمتوسط بفضل أسنانها المتداخلة المتقنة التي تضمن ثباتاً يدوم لساعات دون إجهاد لفروة الرأس.",
    fabricDetails: "أسيتات السليلوز الفاخر بتشطيب لامع ومقبض مريح",
    price: 240,
    salePrice: 190,
    stock: 25,
    categoryId: 8,
    categoryName: "توك وإكسسوارات شعر",
    categorySlug: "hair-clips",
    sizes: ["مقاس موحد"],
    colors: [
      { name: "عنابي مارون لامع", hex: "#881337" },
      { name: "أسود كلاسيك", hex: "#111827" },
      { name: "أزرق ملكي داكن", hex: "#1e3a8a" },
      { name: "وردي ناعم", hex: "#db2777" },
    ],
    images: [
      "https://res.cloudinary.com/dnhydbrvc/image/upload/f_auto,q_auto/modanil_hairclips/modanil_hairclips_08.jpg",
      "https://res.cloudinary.com/dnhydbrvc/image/upload/f_auto,q_auto/modanil_hairclips/modanil_hairclips_09.jpg",
    ],
    isFeatured: true,
    isNew: true,
    sku: "ACC-CLP-05",
    hasSizeGuide: false,
    badgeText: "إكسسوار حصري ✨",
  },
  {
    id: 116,
    name: "كلبسة شعر هلالية مرصعة بالستراس الكريستالي الأسود",
    slug: "modanil-luxury-rhinestone-arch-claw-clip",
    description: "قطعة مجوهرات للشعر بتصميم قوسي هلالي مرصع بصفوف دقيقة من الكريستال والستراس اللامع من علامة MODANIL. تضفي بريقاً ساحراً على تسريحات السهرات والمناسبات الخاصة مع أسنان قوية محكمة.",
    fabricDetails: "أكريليك فاخر مقوى ومرصع بحبيبات الكريستال اللامعة",
    price: 280,
    salePrice: 230,
    stock: 18,
    categoryId: 8,
    categoryName: "توك وإكسسوارات شعر",
    categorySlug: "hair-clips",
    sizes: ["مقاس موحد"],
    colors: [
      { name: "أسود كريستالي لامع", hex: "#0f172a" },
    ],
    images: [
      "https://res.cloudinary.com/dnhydbrvc/image/upload/f_auto,q_auto/modanil_hairclips/modanil_hairclips_10.jpg",
      "https://res.cloudinary.com/dnhydbrvc/image/upload/f_auto,q_auto/modanil_hairclips/modanil_hairclips_17.jpg",
      "https://res.cloudinary.com/dnhydbrvc/image/upload/f_auto,q_auto/modanil_hairclips/modanil_hairclips_21.jpg",
    ],
    isFeatured: true,
    isNew: true,
    sku: "ACC-CLP-06",
    hasSizeGuide: false,
    badgeText: "إكسسوار حصري ✨",
  },
  {
    id: 117,
    name: "طقم بنس شعر تيك تاك بدرجات أزرق المحيط المتدرجة (8 قطع)",
    slug: "modanil-ocean-gradient-snap-clips-set",
    description: "طقم أنيق مكون من 8 بنس شعر تيك تاك بألوان مستوحاة من زرقة المحيط المتدرجة من الأزرق الداكن وحتى السماوي الفاتح. مصنوعة بتشطيب ناعم لا يشد الشعر ومثالية للإطلالات الصيفية والحيوية.",
    fabricDetails: "معدن مرن مغطى بطلاء مينا ناعم غير قابل للخدش",
    price: 160,
    salePrice: 130,
    stock: 25,
    categoryId: 8,
    categoryName: "توك وإكسسوارات شعر",
    categorySlug: "hair-clips",
    sizes: ["مقاس موحد"],
    colors: [
      { name: "تدرجات الأزرق السماوي", hex: "#0284c7" },
    ],
    images: [
      "https://res.cloudinary.com/dnhydbrvc/image/upload/f_auto,q_auto/modanil_hairclips/modanil_hairclips_11.jpg",
    ],
    isFeatured: false,
    isNew: true,
    sku: "ACC-CLP-07",
    hasSizeGuide: false,
    badgeText: "إكسسوار حصري ✨",
  },
  {
    id: 118,
    name: "طقم كلبسات شعر تايجر عسلي وألوان كلاسيكية ناعمة",
    slug: "modanil-tortoise-neutral-claw-clips-set",
    description: "كلبسات شعر كلاسيكية فاخرة بنقشة جلد السلحفاة (Tortoise Shell) والدرجات الحيادية الأنيقة. مزودة بقبضة قوية مانعة للانزلاق تناسب الإطلالات اليومية والعملية الفاخرة.",
    fabricDetails: "راتنج طبيعي بتشطيب رخامي وعسلي عالي اللمعان",
    price: 210,
    salePrice: 170,
    stock: 22,
    categoryId: 8,
    categoryName: "توك وإكسسوارات شعر",
    categorySlug: "hair-clips",
    sizes: ["مقاس موحد"],
    colors: [
      { name: "تايجر عسلي فاخر", hex: "#78350f" },
      { name: "لاتيه نود كريمي", hex: "#e5e5e5" },
      { name: "أسود داكن", hex: "#171717" },
    ],
    images: [
      "https://res.cloudinary.com/dnhydbrvc/image/upload/f_auto,q_auto/modanil_hairclips/modanil_hairclips_12.jpg",
    ],
    isFeatured: false,
    isNew: true,
    sku: "ACC-CLP-08",
    hasSizeGuide: false,
    badgeText: "إكسسوار حصري ✨",
  },
  {
    id: 119,
    name: "طقم توك وطوق شعر فرو شتوي فائق النعومة (3 قطع)",
    slug: "modanil-winter-plush-scrunchies-headband-set",
    description: "مجموعة شتوية دافئة وناعمة مكونة من طوق شعر مغلف بفرو ناعم مع توك شعر سكرانشي فخمة من خامة الفرو المخملي. تمنحك إطلالة شتوية أنيقة تحافظ على راحة الشعر طوال اليوم.",
    fabricDetails: "فرو تيدي ناعم فاخر مع أربطة مطاطية مرنة لا تقصف الشعر",
    price: 260,
    salePrice: 210,
    stock: 20,
    categoryId: 8,
    categoryName: "توك وإكسسوارات شعر",
    categorySlug: "hair-clips",
    sizes: ["مقاس موحد"],
    colors: [
      { name: "جملي دافئ", hex: "#b45309" },
      { name: "أبيض ثلجي", hex: "#f8fafc" },
      { name: "موف رمادي ناعم", hex: "#a855f7" },
    ],
    images: [
      "https://res.cloudinary.com/dnhydbrvc/image/upload/f_auto,q_auto/modanil_hairclips/modanil_hairclips_13.jpg",
      "https://res.cloudinary.com/dnhydbrvc/image/upload/f_auto,q_auto/modanil_hairclips/modanil_hairclips_14.jpg",
      "https://res.cloudinary.com/dnhydbrvc/image/upload/f_auto,q_auto/modanil_hairclips/modanil_hairclips_16.jpg",
    ],
    isFeatured: true,
    isNew: true,
    sku: "ACC-CLP-09",
    hasSizeGuide: false,
    badgeText: "إكسسوار حصري ✨",
  },
  {
    id: 120,
    name: "طقم أربطة وتوك شعر قطنية بدون خياطة بألوان الباستيل",
    slug: "modanil-pastel-cotton-hair-bands-set",
    description: "مجموعة أربطة وتوك شعر ناعمة مصنوعة من خيوط قطنية فائقة المرونة بتصميم سلس بدون درزات معدنية لحماية الشعر من الشد أو التقصف. ألوان هادئة كلاسيكية مناسبة للاستخدام اليومي والرياضي.",
    fabricDetails: "مزيج قطن مطاطي ناعم 100% بدون وصلات معدنية",
    price: 170,
    salePrice: 135,
    stock: 35,
    categoryId: 8,
    categoryName: "توك وإكسسوارات شعر",
    categorySlug: "hair-clips",
    sizes: ["مقاس موحد"],
    colors: [
      { name: "نعناعي باستيل", hex: "#86efac" },
      { name: "وردي فاتح", hex: "#f472b6" },
      { name: "لافندر بنفسجي", hex: "#c084fc" },
    ],
    images: [
      "https://res.cloudinary.com/dnhydbrvc/image/upload/f_auto,q_auto/modanil_hairclips/modanil_hairclips_15.jpg",
      "https://res.cloudinary.com/dnhydbrvc/image/upload/f_auto,q_auto/modanil_hairclips/modanil_hairclips_22.jpg",
    ],
    isFeatured: false,
    isNew: true,
    sku: "ACC-CLP-10B",
    hasSizeGuide: false,
    badgeText: "إكسسوار حصري ✨",
  },
  {
    id: 121,
    name: "طقم تصفيف وتزيين الشعر بنقشة السفاري والتايجر",
    slug: "modanil-safari-satin-scrunchie-styling-kit",
    description: "طقم تصفيف متكامل لعشاق الأناقة والجاذبية بنقشات الزيبرا والنمر البري الفاخرة. يضم سكرانشي ستان حريري لامع، وطوق رأس رفيع فاخر، وبنس ومساكات شعر مطابقة لإطلالة استثنائية وجذابة.",
    fabricDetails: "ستان حريري ناعم - إكسسوارات أكريليك ومعدن مطلي",
    price: 250,
    salePrice: 199,
    stock: 18,
    categoryId: 8,
    categoryName: "توك وإكسسوارات شعر",
    categorySlug: "hair-clips",
    sizes: ["مقاس موحد"],
    colors: [
      { name: "زيبرا ذهبي وأسود", hex: "#18181b" },
      { name: "تايجر موكا وبني", hex: "#78350f" },
    ],
    images: [
      "https://res.cloudinary.com/dnhydbrvc/image/upload/f_auto,q_auto/modanil_hairclips/modanil_hairclips_18.jpg",
      "https://res.cloudinary.com/dnhydbrvc/image/upload/f_auto,q_auto/modanil_hairclips/modanil_hairclips_19.jpg",
      "https://res.cloudinary.com/dnhydbrvc/image/upload/f_auto,q_auto/modanil_hairclips/modanil_hairclips_20.jpg",
    ],
    isFeatured: true,
    isNew: true,
    sku: "ACC-CLP-11",
    hasSizeGuide: false,
    badgeText: "إكسسوار حصري ✨",
  },
  {
    id: 122,
    name: "كلبسة شعر فيونكة شيفون منقطة أوفر سايز باللونين الأبيض والأسود",
    slug: "modanil-dotted-chiffon-bow-claw-clip",
    description: "كلبسة شعر مميزة بفيونكة قماشية كبيرة من الشيفون الحريري المنقط بنمط Polka Dot الكلاسيكي مع مشبك قوي أسود يثبت الشعر باحترافية وأناقة في أرقى المناسبات.",
    fabricDetails: "شيفون بولكا دوت ناعم مع مشبك شعر أكريليك متين",
    price: 230,
    salePrice: 180,
    stock: 22,
    categoryId: 8,
    categoryName: "توك وإكسسوارات شعر",
    categorySlug: "hair-clips",
    sizes: ["مقاس موحد"],
    colors: [
      { name: "منقط أبيض وأسود", hex: "#111827" },
    ],
    images: [
      "https://res.cloudinary.com/dnhydbrvc/image/upload/f_auto,q_auto/modanil_hairclips/modanil_hairclips_23.jpg",
    ],
    isFeatured: true,
    isNew: true,
    sku: "ACC-CLP-12",
    hasSizeGuide: false,
    badgeText: "إكسسوار حصري ✨",
  },
  {
    id: 123,
    name: "طقم توك ومساكات شعر فيونكة أورجانزا وردية بحبة الورد الحريرية",
    slug: "modanil-organza-silk-rose-ribbon-bow-set",
    description: "طقم فيونكات أورجانزا ناعمة ومضيئة بلمسة وردة باريسية مفرغة في المنتصف ومشبك معدني فرنسي دقيق. متوفر بألوان الباستيل الفاخرة لتسريحات ملكية رقيقة وجذابة.",
    fabricDetails: "قماش أورجانزا شفاف وستان ناعم مع مشبك فرنسي معدني",
    price: 245,
    salePrice: 195,
    stock: 24,
    categoryId: 8,
    categoryName: "توك وإكسسوارات شعر",
    categorySlug: "hair-clips",
    sizes: ["مقاس موحد"],
    colors: [
      { name: "وردي بلش ناعم", hex: "#f472b6" },
      { name: "عاجي لؤلؤي", hex: "#fef3c7" },
      { name: "برونزي ذهبي", hex: "#b45309" },
      { name: "أسود شفاف", hex: "#111827" },
    ],
    images: [
      "https://res.cloudinary.com/dnhydbrvc/image/upload/f_auto,q_auto/modanil_hairclips/modanil_hairclips_24.jpg",
      "https://res.cloudinary.com/dnhydbrvc/image/upload/f_auto,q_auto/modanil_hairclips/modanil_hairclips_25.jpg",
    ],
    isFeatured: true,
    isNew: true,
    sku: "ACC-CLP-13",
    hasSizeGuide: false,
    badgeText: "إكسسوار حصري ✨",
  },
  {
    id: 124,
    name: "طقم كلبسات شعر بتلات الورد الكريستالية اللامعة (قطعتين)",
    slug: "modanil-crystal-flower-petal-claw-clips",
    description: "زوج من كلبسات الشعر بتصميم زهرة استوائية براقة ببتلات كريستالية عاكسة للضوء ولمسة لؤلؤية وردية. مشبك زنبركي دقيق ومحكم لتثبيت الشعر الجانبي وإضفاء إشراقة أنثوية فورية.",
    fabricDetails: "أكريليك هولوجرامي عاكس للضوء مع طلاء لؤلؤي مقاوم للخدش",
    price: 215,
    salePrice: 170,
    stock: 20,
    categoryId: 8,
    categoryName: "توك وإكسسوارات شعر",
    categorySlug: "hair-clips",
    sizes: ["مقاس موحد"],
    colors: [
      { name: "وردي كريستال عاكس", hex: "#f472b6" },
      { name: "وردي لؤلؤي ناعم", hex: "#fda4af" },
    ],
    images: [
      "https://res.cloudinary.com/dnhydbrvc/image/upload/f_auto,q_auto/modanil_hairclips/modanil_hairclips_26.jpg",
    ],
    isFeatured: true,
    isNew: true,
    sku: "ACC-CLP-14",
    hasSizeGuide: false,
    badgeText: "إكسسوار حصري ✨",
  },
  {
    id: 125,
    name: "مجموعة بنس وتوك مخملية ناعمة للشعر (8 قطع)",
    slug: "modanil-velvet-snap-clips-hair-ties-set",
    description: "تشكيلة متناسقة تضم 4 بنس شعر تيك تاك عصرية مع 4 توك شعر مخملية قطيفة عريضة وفائقة الراحة. خامات لطيفة تحافظ على ملمس الشعر وتمنع التكسر مع ثبات يدوم طوال اليوم.",
    fabricDetails: "قماش مخمل قطيفة ناعم مع معدن كربوني محمي بطبقة سيليكون ناعمة",
    price: 175,
    salePrice: 140,
    stock: 30,
    categoryId: 8,
    categoryName: "توك وإكسسوارات شعر",
    categorySlug: "hair-clips",
    sizes: ["مقاس موحد"],
    colors: [
      { name: "درجات ترابية ونود", hex: "#78350f" },
      { name: "درجات ماكرون وباستيل", hex: "#fbcfe8" },
    ],
    images: [
      "https://res.cloudinary.com/dnhydbrvc/image/upload/f_auto,q_auto/modanil_hairclips/modanil_hairclips_27.jpg",
      "https://res.cloudinary.com/dnhydbrvc/image/upload/f_auto,q_auto/modanil_hairclips/modanil_hairclips_28.jpg",
    ],
    isFeatured: false,
    isNew: true,
    sku: "ACC-CLP-15",
    hasSizeGuide: false,
    badgeText: "إكسسوار حصري ✨",
  },
  {
    id: 126,
    name: "طقم مساكات شعر فيونكة أورجانزا سوداء ملكية بحبة الورد الحريرية (قطعتين)",
    slug: "modanil-royal-black-organza-rose-hair-clips",
    description: "زوج فاخر من مساكات الشعر بتصميم فيونكة أورجانزا ملكية باللون الأسود الكلاسيكي مع وردة باريسية ملفوفة من الستان الحريري في المنتصف. مزودة بمشبك فرنسي دقيق يضمن ثباتاً أنيقاً ومريحاً لمختلف التسريحات والمناسبات المسائية.",
    fabricDetails: "قماش أورجانزا فاخر شفاف وستان حريري ناعم مع مشبك معدني فرنسي أسود متين",
    price: 245,
    salePrice: 195,
    stock: 24,
    categoryId: 8,
    categoryName: "توك وإكسسوارات شعر",
    categorySlug: "hair-clips",
    sizes: ["مقاس موحد"],
    colors: [
      { name: "أسود ملكي فاخر", hex: "#111827" },
    ],
    images: [
      "https://res.cloudinary.com/dnhydbrvc/image/upload/f_auto,q_auto/modanil_hairclips/modanil_hairclips_29.jpg",
    ],
    isFeatured: true,
    isNew: true,
    sku: "ACC-CLP-16",
    hasSizeGuide: false,
    badgeText: "إكسسوار حصري ✨",
  },
  {
    id: 127,
    name: "طقم سكرانشي شعر فرو قطيفة بشخصيات الكرتون والكاواي مع أربطة مطاطية",
    slug: "modanil-kawaii-plush-character-scrunchie-set",
    description: "تشكيلة سكرانشي شعر شتوية فائقة النعومة مصنوعة من الفرو القطيفة الفاخر، مزينة بمجسمات سيليكون ثلاثية الأبعاد لأشهر شخصيات الكرتون والكاواي (كورومي، ميلودي، كيروبي، سينامورول، بومبومبورين)، مصحوبة بزوج من أربطة الشعر المطاطية المتناسقة لحماية الشعر وإضفاء بهجة عصرية مرحة.",
    fabricDetails: "فرو قطيفة ناعم عالي الكثافة مع مجسمات سيليكون مرنة وأربطة قطن مطاطية بدون درزات",
    price: 210,
    salePrice: 165,
    stock: 35,
    categoryId: 8,
    categoryName: "توك وإكسسوارات شعر",
    categorySlug: "hair-clips",
    sizes: ["مقاس موحد"],
    colors: [
      { name: "لافندر كورومي", hex: "#c084fc" },
      { name: "رمادي كيروبي", hex: "#9ca3af" },
      { name: "وردي ميلودي", hex: "#f472b6" },
      { name: "سماوي سينامورول", hex: "#7dd3fc" },
      { name: "بيج بومبومبورين", hex: "#fef08a" },
    ],
    images: [
      "https://res.cloudinary.com/dnhydbrvc/image/upload/f_auto,q_auto/modanil_hairclips/modanil_hairclips_31.jpg",
      "https://res.cloudinary.com/dnhydbrvc/image/upload/f_auto,q_auto/modanil_hairclips/modanil_hairclips_30.jpg",
      "https://res.cloudinary.com/dnhydbrvc/image/upload/f_auto,q_auto/modanil_hairclips/modanil_hairclips_35.jpg",
    ],
    isFeatured: true,
    isNew: true,
    sku: "ACC-CLP-17",
    hasSizeGuide: false,
    badgeText: "الأكثر طلباً 🔥",
  },
  {
    id: 128,
    name: "طقم مساكات شعر كليب منقار البط بشخصيات الكاواي الكرتونية (4 قطع)",
    slug: "modanil-kawaii-alligator-clips-set",
    description: "مجموعة مميزة من مساكات شعر الأكريليك والمعدن بتصميم منقار البط العملي، مزينة بمجسمات بارزة ثلاثية الأبعاد لشخصيات الكاواي المحبوبة (سينامورول، هالو كيتي، كورومي، ميلودي، بومبومبورين). تصميم مزدوج يجمع بين الكليب المصمت والكليب المفرغ الشفاف لتنسيق تسريحات مفعمة بالحيوية.",
    fabricDetails: "هيكل معدني ملون ومقاوم للصدأ مع مجسمات سيليكون ناعمة ومريحة لفروة الرأس",
    price: 195,
    salePrice: 155,
    stock: 28,
    categoryId: 8,
    categoryName: "توك وإكسسوارات شعر",
    categorySlug: "hair-clips",
    sizes: ["مقاس موحد"],
    colors: [
      { name: "أزرق سماوي سينامورول", hex: "#38bdf8" },
      { name: "بنفسجي كورومي", hex: "#a855f7" },
      { name: "وردي كيتي وميلودي", hex: "#f472b6" },
      { name: "أصفر بومبومبورين", hex: "#facc15" },
    ],
    images: [
      "https://res.cloudinary.com/dnhydbrvc/image/upload/f_auto,q_auto/modanil_hairclips/modanil_hairclips_32.jpg",
      "https://res.cloudinary.com/dnhydbrvc/image/upload/f_auto,q_auto/modanil_hairclips/modanil_hairclips_33.jpg",
    ],
    isFeatured: true,
    isNew: true,
    sku: "ACC-CLP-18",
    hasSizeGuide: false,
    badgeText: "إكسسوار حصري ✨",
  },
  {
    id: 129,
    name: "طقم أربطة شعر فيونكة كرز الستان الأخضر بحبات الكريستال العنابية (قطعتين)",
    slug: "modanil-emerald-green-cherry-satin-hair-ties",
    description: "توكة شعر فاخرة بتصميم مستوحى من الطبيعة تضم فيونكة ستان حريرية بلون الأخضر الزمردي الراقي مع ثمار كرز كريستالية عنابية شفافة تعكس الضوء ببريق جذاب. مصنوعة يدوياً بحرفية استثنائية من MODANIL لإطلالة مفعمة بالأنوثة والتميز.",
    fabricDetails: "شريط ستان حريري مزدوج، حبات كرز أكريليك كريستالي عالي اللمعان، شريط مطاطي مزدوج عالي التحمل",
    price: 225,
    salePrice: 175,
    stock: 26,
    categoryId: 8,
    categoryName: "توك وإكسسوارات شعر",
    categorySlug: "hair-clips",
    sizes: ["مقاس موحد"],
    colors: [
      { name: "أخضر زمردي مع عنابي", hex: "#047857" },
    ],
    images: [
      "https://res.cloudinary.com/dnhydbrvc/image/upload/f_auto,q_auto/modanil_hairclips/modanil_hairclips_42.jpg",
      "https://res.cloudinary.com/dnhydbrvc/image/upload/f_auto,q_auto/modanil_hairclips/modanil_hairclips_34.jpg",
    ],
    isFeatured: true,
    isNew: true,
    sku: "ACC-CLP-19",
    hasSizeGuide: false,
    badgeText: "صناعة يدوية فاخرة ✨",
  },
  {
    id: 130,
    name: "طقم مساكات شعر الفراشات الملونة البارزة مع أربطة قطنية باستيل (10 قطع)",
    slug: "modanil-embossed-butterfly-clips-and-pastel-elastics-set",
    description: "مجموعة متكاملة لإطلالة صيفية مشرقة تضم 4 كلبسات شعر بتصميم فراشات ثلاثية الأبعاد بنقوش وتفاصيل دقيقة بألوان الباستيل المبهجة (وردي، سماوي، فوشيا، ليموني)، بالإضافة إلى 6 أربطة شعر قطنية ناعمة بدون خياطة لحماية الشعر من التشابك.",
    fabricDetails: "مجسمات فراشة سيليكون 3D على كليب معدني أسود مبطن + أربطة قطنية مرنة",
    price: 190,
    salePrice: 150,
    stock: 30,
    categoryId: 8,
    categoryName: "توك وإكسسوارات شعر",
    categorySlug: "hair-clips",
    sizes: ["مقاس موحد"],
    colors: [
      { name: "تشكيلة فراشات باستيل ملونة", hex: "#f472b6" },
    ],
    images: [
      "https://res.cloudinary.com/dnhydbrvc/image/upload/f_auto,q_auto/modanil_hairclips/modanil_hairclips_36.jpg",
    ],
    isFeatured: false,
    isNew: true,
    sku: "ACC-CLP-20",
    hasSizeGuide: false,
    badgeText: "إكسسوار حصري ✨",
  },
  {
    id: 131,
    name: "طقم مساكات شعر يونيكورن السحري ثلاثي الأبعاد مع أربطة باستيل (10 قطع)",
    slug: "modanil-magical-unicorn-clips-and-pastel-elastics-set",
    description: "مجموعة أحلام الطفولة والأناقة العصرية تضم 4 مشابك شعر كليب لشخصيات اليونيكورن وبيغاسوس المجنح ثلاثية الأبعاد بلمسات الباستيل والقلوب الوردية، بالإضافة إلى 6 أربطة شعر باستيلية قطنية فائقة النعومة والمرونة.",
    fabricDetails: "سيليكون ناعم عالي الجودة مع كليب معدني مبطن وأربطة شعر قطن ليكرا ناعمة",
    price: 195,
    salePrice: 155,
    stock: 25,
    categoryId: 8,
    categoryName: "توك وإكسسوارات شعر",
    categorySlug: "hair-clips",
    sizes: ["مقاس موحد"],
    colors: [
      { name: "يونيكورن أبيض وسماوي باستيل", hex: "#e0e7ff" },
    ],
    images: [
      "https://res.cloudinary.com/dnhydbrvc/image/upload/f_auto,q_auto/modanil_hairclips/modanil_hairclips_37.jpg",
    ],
    isFeatured: false,
    isNew: true,
    sku: "ACC-CLP-21",
    hasSizeGuide: false,
    badgeText: "إكسسوار حصري ✨",
  },
  {
    id: 132,
    name: "طقم كلبسات شعر القلوب الباستيل المجسمة بإطار مموج مع أربطة قطنية (10 قطع)",
    slug: "modanil-scalloped-3d-hearts-clips-elastics-set",
    description: "طقم رومانسي ناعم يجمع بين 4 كلبسات شعر بتصميم قلوب ثلاثية الأبعاد غير لامعة (Matte) بإطار حلزوني مموج بلونين متناسقين (مرجاني، سماوي، وردي، بنفسجي نعناعي) مع 6 أربطة شعر قطنية متناسقة لحماية الشعر وتنسيق أروع التسريحات اليومية.",
    fabricDetails: "أكريليك مطفي ناعم الملمس، كليب معدني أسود متين، أربطة مرنة ناعمة الملمس",
    price: 185,
    salePrice: 145,
    stock: 32,
    categoryId: 8,
    categoryName: "توك وإكسسوارات شعر",
    categorySlug: "hair-clips",
    sizes: ["مقاس موحد"],
    colors: [
      { name: "درجات قلوب باستيل مبهجة", hex: "#fda4af" },
    ],
    images: [
      "https://res.cloudinary.com/dnhydbrvc/image/upload/f_auto,q_auto/modanil_hairclips/modanil_hairclips_38.jpg",
    ],
    isFeatured: false,
    isNew: true,
    sku: "ACC-CLP-22",
    hasSizeGuide: false,
    badgeText: "إكسسوار حصري ✨",
  },
  {
    id: 133,
    name: "طقم بنس شعر معدنية مفرغة بألوان الباستيل ومجسمات الورد الكورية (4 قطع)",
    slug: "modanil-pastel-geometric-flower-snap-clips-set",
    description: "تشكيلة أنيقة من مساكات الشعر الهندسية المفرغة بطلاء الإيناميل الباستيلي اللامع والمقاوم للخدش، مزدانة بزهور ناعمة ثلاثية الأبعاد بقلب ملون. تثبيت محكم وسهل الفتح والإغلاق يمنح إطلالتك لمسة كورية رقيقة ومفعمة بالحيوية.",
    fabricDetails: "معدن مطلي بطبقة إيناميل ناعمة ومجسمات راتنج بارزة مقاومة للبهتان",
    price: 180,
    salePrice: 140,
    stock: 30,
    categoryId: 8,
    categoryName: "توك وإكسسوارات شعر",
    categorySlug: "hair-clips",
    sizes: ["مقاس موحد"],
    colors: [
      { name: "ألوان زهور الباستيل المتعددة", hex: "#f472b6" },
      { name: "أزرق سماوي وأصفر", hex: "#38bdf8" },
      { name: "لافندر بنفسجي", hex: "#c084fc" },
    ],
    images: [
      "https://res.cloudinary.com/dnhydbrvc/image/upload/f_auto,q_auto/modanil_hairclips/modanil_hairclips_40.jpg",
      "https://res.cloudinary.com/dnhydbrvc/image/upload/f_auto,q_auto/modanil_hairclips/modanil_hairclips_39.jpg",
    ],
    isFeatured: false,
    isNew: true,
    sku: "ACC-CLP-23",
    hasSizeGuide: false,
    badgeText: "إكسسوار حصري ✨",
  },
  {
    id: 134,
    name: "طقم تصفيف وتزيين شعر ديزني الفاخر مع سكرانشي كشكش وبنس مميزة (5 قطع)",
    slug: "modanil-character-ruffled-scrunchie-styling-gift-set",
    description: "مجموعة تصفيف استثنائية متكاملة تضم سكرانشي كشكش فاخر مزين بمجسم شخصية كرتونية محبوبة (ديزي داك الوردية أو لوتسو بيري التوتي)، مع 4 إكسسوارات شعر منتقاة بعناية تشمل كلبسة قلب مموج، بنسة عروسة أنيقة، كلبسة زهرة بارزة، وفيونكة بولكا دوت منقطة كلاسيكية.",
    fabricDetails: "قماش كريب قطني مكشكش مع إكسسوارات سيليكون وراتنج فاخرة وكليب معدني مبطن",
    price: 260,
    salePrice: 205,
    stock: 22,
    categoryId: 8,
    categoryName: "توك وإكسسوارات شعر",
    categorySlug: "hair-clips",
    sizes: ["مقاس موحد"],
    colors: [
      { name: "وردي ديزي داك الرقيق", hex: "#f472b6" },
      { name: "فوشيا وتوتي لوتسو الفاخر", hex: "#be185d" },
    ],
    images: [
      "https://res.cloudinary.com/dnhydbrvc/image/upload/f_auto,q_auto/modanil_hairclips/modanil_hairclips_41.jpg",
      "https://res.cloudinary.com/dnhydbrvc/image/upload/f_auto,q_auto/modanil_hairclips/modanil_hairclips_43.jpg",
    ],
    isFeatured: true,
    isNew: true,
    sku: "ACC-CLP-24",
    hasSizeGuide: false,
    badgeText: "طقم إهداء فاخر 🎁",
  },
];

export const INITIAL_PRODUCTS: ProductItem[] = RAW_INITIAL_PRODUCTS.map((p) => {
  const variants = buildProductVariants(p.id, p.sku || `SKU-${p.id}`, p.sizes, p.colors, p.salePrice || p.price);
  return {
    ...p,
    variants,
    stock: variants.reduce((sum, v) => sum + v.stock, 0),
  };
});

export const INITIAL_ORDERS: OrderItem[] = [
  {
    id: 1001,
    orderNumber: "EG-2026-8941",
    customerName: "أحمد مصطفى الديب",
    customerPhone: "01012458971",
    alternatePhone: "01145896321",
    governorate: "القاهرة",
    city: "مدينة نصر",
    address: "شارع الطيران، متفرع من عباس العقاد، عمارة 24، الدور الثالث، شقة 6",
    notes: "يرجى الاتصال قبل الوصول بنصف ساعة",
    paymentMethod: "cod",
    paymentStatus: "pending",
    orderStatus: "new",
    items: [
      {
        productId: 101,
        name: "تيشيرت أوفر سايز بيزك - قطن مصري فاخر",
        size: "XL",
        color: "أسود ملكي",
        price: 380,
        quantity: 2,
        image: "https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=800&auto=format&fit=crop&q=80",
      },
      {
        productId: 104,
        name: "بنطلون كارجو عملي بجيوب جانبية متعددة",
        size: "34",
        color: "زيتي عسكري",
        price: 490,
        quantity: 1,
        image: "https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=800&auto=format&fit=crop&q=80",
      },
    ],
    subtotal: 1250,
    shippingFee: 45,
    discount: 50,
    couponCode: "WELCOME50",
    total: 1245,
    createdAt: "2026-09-09T14:30:00.000Z",
  },
  {
    id: 1002,
    orderNumber: "EG-2026-8942",
    customerName: "سارة الشريف",
    customerPhone: "01289654123",
    governorate: "الإسكندرية",
    city: "سموحة",
    address: "أبراج الصيادلة، شارع فوزي معاذ، برج رقم 2، شقة 14",
    notes: "تم التحويل على إنستاباي بنجاح",
    paymentMethod: "instapay",
    paymentStatus: "paid",
    orderStatus: "processing",
    items: [
      {
        productId: 105,
        name: "دريس كاجوال طويل بحزام خصر - ناعم ومريح",
        size: "M",
        color: "أخضر زمردي",
        price: 750,
        quantity: 1,
        image: "https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=800&auto=format&fit=crop&q=80",
      },
    ],
    subtotal: 750,
    shippingFee: 55,
    discount: 0,
    total: 805,
    createdAt: "2026-09-08T19:15:00.000Z",
  },
  {
    id: 1003,
    orderNumber: "EG-2026-8943",
    customerName: "محمود عبد العزيز قاسم",
    customerPhone: "01156987412",
    governorate: "الجيزة",
    city: "الشيخ زايد",
    address: "كمبوند بيفرلي هيلز، المرحلة الثانية، فيلا 18",
    notes: "",
    paymentMethod: "cod",
    paymentStatus: "paid",
    orderStatus: "delivered",
    items: [
      {
        productId: 102,
        name: "هودي ميلتون ثقيل مبطن كابيشو - كايرو إديشن",
        size: "L",
        color: "كحلي داكن",
        price: 690,
        quantity: 1,
        image: "https://images.unsplash.com/photo-1556905055-8f358a7a47b2?w=800&auto=format&fit=crop&q=80",
      },
      {
        productId: 106,
        name: "بليزر كاجوال إيطالي سليم فيت",
        size: "52",
        color: "رمادي غامق",
        price: 1090,
        quantity: 1,
        image: "https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=800&auto=format&fit=crop&q=80",
      },
    ],
    subtotal: 1780,
    shippingFee: 0, // Free shipping threshold applied!
    discount: 0,
    total: 1780,
    trackingNumber: "BOSTA-EG-998822",
    createdAt: "2026-09-06T11:00:00.000Z",
  },
  {
    id: 1004,
    orderNumber: "EG-2026-8944",
    customerName: "طارق النجار",
    customerPhone: "01099887766",
    governorate: "الدقهلية (المنصورة)",
    city: "حي الجامعة",
    address: "شارع جيهان، أمام بوابة جامعة المنصورة، عمارة البرج، الدور الخامس",
    notes: "الدفع فودافون كاش",
    paymentMethod: "vodafone_cash",
    paymentStatus: "paid",
    orderStatus: "shipped",
    items: [
      {
        productId: 103,
        name: "قميص كتان طبيعي صيفي خفيف",
        size: "XL",
        color: "أبيض صيفي",
        price: 520,
        quantity: 2,
        image: "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=800&auto=format&fit=crop&q=80",
      },
    ],
    subtotal: 1040,
    shippingFee: 55,
    discount: 100,
    couponCode: "EGYPT100",
    total: 995,
    trackingNumber: "Mylerz-EG-54210",
    createdAt: "2026-09-07T16:20:00.000Z",
  },
];

export const INITIAL_COUPONS: CouponItem[] = [
  {
    id: 1,
    code: "WELCOME50",
    discountType: "fixed",
    discountValue: 50,
    minOrderValue: 400,
    usageLimit: 500,
    usedCount: 34,
    isActive: true,
  },
  {
    id: 2,
    code: "EGYPT20",
    discountType: "percentage",
    discountValue: 20,
    minOrderValue: 600,
    usageLimit: 200,
    usedCount: 18,
    isActive: true,
  },
  {
    id: 3,
    code: "SUMMER15",
    discountType: "percentage",
    discountValue: 15,
    minOrderValue: 350,
    usageLimit: 100,
    usedCount: 12,
    isActive: true,
  },
];

import { STORE_DEFAULTS } from "@/lib/egypt-constants";

export const INITIAL_SETTINGS: StoreSettingsItem = {
  storeName: STORE_DEFAULTS.storeName,
  phone: STORE_DEFAULTS.phone,
  whatsapp: STORE_DEFAULTS.whatsapp,
  supportEmail: STORE_DEFAULTS.supportEmail,
  instapayHandle: STORE_DEFAULTS.instapayHandle,
  instapayPhone: STORE_DEFAULTS.phone,
  vodafoneCashPhone: STORE_DEFAULTS.vodafoneCashPhone,
  freeShippingThreshold: STORE_DEFAULTS.freeShippingThreshold,
  bannerNotice: STORE_DEFAULTS.bannerNotice,
  isBannerActive: true,
  isAcceptingOrders: true,
  isMaintenanceMode: false,
  estimatedDeliveryDays: STORE_DEFAULTS.estimatedDeliveryDays,
  enabledPaymentMethods: ["cod", "instapay", "vodafone_cash", "card"],
  orderClosedMessage: STORE_DEFAULTS.orderClosedMessage,
  maintenanceMessage: STORE_DEFAULTS.maintenanceMessage,
  // Branding & Assets
  logoUrl: STORE_DEFAULTS.logoUrl,
  storeTagline: STORE_DEFAULTS.storeTagline,
  storeDescription: STORE_DEFAULTS.storeDescription,
  // Location & Social
  physicalAddress: STORE_DEFAULTS.physicalAddress,
  landlinePhone: STORE_DEFAULTS.landlinePhone,
  secondaryPhone: STORE_DEFAULTS.secondaryPhone,
  supportWhatsapp: STORE_DEFAULTS.supportWhatsapp,
  workingHours: STORE_DEFAULTS.workingHours,
  googleMapsUrl: STORE_DEFAULTS.googleMapsUrl,
  telegramUrl: STORE_DEFAULTS.telegramUrl,
  facebookUrl: STORE_DEFAULTS.facebookUrl,
  instagramUrl: STORE_DEFAULTS.instagramUrl,
  tiktokUrl: STORE_DEFAULTS.tiktokUrl,
  // Hero CMS
  heroBadge: STORE_DEFAULTS.heroBadge,
  heroTitle: STORE_DEFAULTS.heroTitle,
  heroSubtitle: STORE_DEFAULTS.heroSubtitle,
  heroBgImage: STORE_DEFAULTS.heroBgImage,
  heroPrimaryBtnText: STORE_DEFAULTS.heroPrimaryBtnText,
  heroPrimaryBtnLink: STORE_DEFAULTS.heroPrimaryBtnLink,
  // Special Promo Banner
  isPromoBannerActive: STORE_DEFAULTS.isPromoBannerActive,
  promoBadge: STORE_DEFAULTS.promoBadge,
  promoTitle: STORE_DEFAULTS.promoTitle,
  promoDescription: STORE_DEFAULTS.promoDescription,
  promoCouponCode: STORE_DEFAULTS.promoCouponCode,
  // SEO Defaults
  seoTitle: STORE_DEFAULTS.seoTitle,
  seoDescription: STORE_DEFAULTS.seoDescription,
  seoKeywords: STORE_DEFAULTS.seoKeywords,
};
