import { CategoryItem, ProductItem, ProductVariantItem, OrderItem, CouponItem, StoreSettingsItem } from "@/types";

export function buildProductVariants(
  productId: number,
  sku: string,
  sizes: string[],
  colors: { name: string; hex: string; imageUrl?: string }[],
  basePrice?: number
): ProductVariantItem[] {
  let varId = productId * 100;
  const variants: ProductVariantItem[] = [];
  for (const s of sizes) {
    for (const c of colors) {
      varId++;
      const cleanColor = c.name.trim().replace(/\s+/g, "");
      variants.push({
        id: varId,
        productId,
        size: s,
        colorName: c.name,
        colorHex: c.hex,
        sku: `${sku || "SKU"}-${s}-${cleanColor}`,
        stock: 5,
        price: basePrice || null,
        imageUrl: c.imageUrl || null,
      });
    }
  }
  return variants;
}

export const INITIAL_CATEGORIES: CategoryItem[] = [
  {
    id: 1,
    name: "أوفر سايز وتي شيرتات",
    slug: "oversized-tshirts",
    image: "https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=800&auto=format&fit=crop&q=80",
    description: "تيشيرتات قطن مصري 100% بقصات عصرية مريحة تناسب جميع الإطلالات الكاجوال",
    displayOrder: 1,
    productsCount: 6,
  },
  {
    id: 2,
    name: "هوديز وسويت شيرت",
    slug: "hoodies-sweatshirts",
    image: "https://images.unsplash.com/photo-1556905055-8f358a7a47b2?w=800&auto=format&fit=crop&q=80",
    description: "ميلتون قطني ثقيل معالج ومبطن بفرو ناعم للدفء والأناقة في شتاء مصر",
    displayOrder: 2,
    productsCount: 5,
  },
  {
    id: 3,
    name: "قمصان كاجوال وكتان",
    slug: "casual-shirts",
    image: "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=800&auto=format&fit=crop&q=80",
    description: "قمصان كتان طبيعي وقطن بيزك تناسب العمل والخروجات الصيفية",
    displayOrder: 3,
    productsCount: 4,
  },
  {
    id: 4,
    name: "بناطيل وسويت بانتس",
    slug: "pants-sweatpants",
    image: "https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=800&auto=format&fit=crop&q=80",
    description: "بناطيل كارجو وجينز مريح وسويت بانتس قطني بأعلى خامات التحمل",
    displayOrder: 4,
    productsCount: 4,
  },
  {
    id: 5,
    name: "ملابس نسائية وكاجوال",
    slug: "women-collection",
    image: "https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=800&auto=format&fit=crop&q=80",
    description: "أطقم دريسات كاجوال، عبايات عصرية، وبليزرات بتصاميم راقية ومحتشمة",
    displayOrder: 5,
    productsCount: 5,
  },
  {
    id: 6,
    name: "بليزرات وجواكت شياكة",
    slug: "blazers-jackets",
    image: "https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=800&auto=format&fit=crop&q=80",
    description: "بليزرات وجواكت وتر بروف وبومبر جاكيت للمناسبات والإطلالات الرسمية",
    displayOrder: 6,
    productsCount: 3,
  },
  {
    id: 7,
    name: "إكسسوارات وشنط",
    slug: "accessories",
    image: "https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=800&auto=format&fit=crop&q=80",
    description: "شنط يد جلدية فاخرة وتوك شعر كورية وإكسسوارات عصرية لإطلالة متكاملة",
    displayOrder: 7,
    productsCount: 2,
  },
];

const RAW_INITIAL_PRODUCTS: ProductItem[] = [
  {
    id: 101,
    name: "تيشيرت أوفر سايز بيزك - قطن مصري فاخر",
    slug: "oversize-basic-tshirt",
    description: "تيشيرت بقصة أوفر سايز عصرية، مصنوع من أجود أنواع خيوط القطن المصري طويل التيلة 100% معالج ضد الانكماش وتغير اللون. مريح للغاية في فصل الصيف ويمتاز بياقة متماسكة لا تتمدد مع الغسيل المتكرر.",
    fabricDetails: "قطن مصري 100% - وزن 240 جرام/م² - تقفيل خياطة مزدوجة",
    price: 490,
    salePrice: 380,
    stock: 25,
    categoryId: 1,
    categoryName: "أوفر سايز وتي شيرتات",
    sizes: ["S", "M", "L", "XL", "2XL"],
    colors: [
      { name: "أسود ملكي", hex: "#111827" },
      { name: "أوف وايت", hex: "#f3f4f6" },
      { name: "زيتي زتونى", hex: "#3f4f38" },
      { name: "رمادي ميلانج", hex: "#6b7280" },
    ],
    images: [
      "https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1618354691373-d851c5c3a990?w=800&auto=format&fit=crop&q=80",
    ],
    isFeatured: true,
    isNew: true,
    sku: "TSH-OVR-01",
  },
  {
    id: 102,
    name: "هودي ميلتون ثقيل مبطن كابيشو - كايرو إديشن",
    slug: "cairo-heavy-hoodie",
    description: "هودي شتوي فائق الدفء بخامة قطن ميلتون مصري 3 خيوط سميكة، جيب كنغر أمامي واسع مع كابيشو مبطن برباط سميك متين. أساور مرنة مريحة.",
    fabricDetails: "ميلتون قطني 85% مع 15% بوليستر مانع للوبرة - وزن 380 جرام",
    price: 850,
    salePrice: 690,
    stock: 14,
    categoryId: 2,
    categoryName: "هوديز وسويت شيرت",
    sizes: ["M", "L", "XL", "2XL", "3XL"],
    colors: [
      { name: "كحلي داكن", hex: "#1e293b" },
      { name: "بيج رملي", hex: "#d7c4a9" },
      { name: "عنابي مارون", hex: "#5b1924" },
    ],
    images: [
      "https://images.unsplash.com/photo-1556905055-8f358a7a47b2?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1509967419530-da38b4704bc6?w=800&auto=format&fit=crop&q=80",
    ],
    isFeatured: true,
    isNew: true,
    sku: "HOD-MIL-02",
  },
  {
    id: 103,
    name: "قميص كتان طبيعي صيفي خفيف",
    slug: "natural-linen-summer-shirt",
    description: "قميص صيفي مصنوع من الكتان والقطن الطبيعي عالي التهوية بياقة ماو (ماندرين) عصرية بدون ربطة عنق، مناسب لأجواء الساحل والصيف في مصر.",
    fabricDetails: "كتان طبيعي 70% + قطن 30% معالج لمقاومة الكرمشة الشديدة",
    price: 680,
    salePrice: 520,
    stock: 18,
    categoryId: 3,
    categoryName: "قمصان كاجوال وكتان",
    sizes: ["M", "L", "XL", "2XL"],
    colors: [
      { name: "أبيض صيفي", hex: "#ffffff" },
      { name: "أزرق سماوي", hex: "#93c5fd" },
      { name: "بيج ترابي", hex: "#caba9c" },
    ],
    images: [
      "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=800&auto=format&fit=crop&q=80",
    ],
    isFeatured: true,
    isNew: false,
    sku: "SHT-LIN-03",
  },
  {
    id: 104,
    name: "بنطلون كارجو عملي بجيوب جانبية متعددة",
    slug: "tactical-cargo-pants",
    description: "بنطلون كارجو بـ 6 جيوب عملية واسعة ومحكمة، قصة ريلكسد مريحة للحركة اليومية، نسيج جبردين مصري قطني متين يتحمل الغسيل والاستخدام الشاق.",
    fabricDetails: "جبردين قطن مصري 100% مع خياطة تريبل مقواة",
    price: 620,
    salePrice: 490,
    stock: 20,
    categoryId: 4,
    categoryName: "بناطيل وسويت بانتس",
    sizes: ["30", "32", "34", "36", "38"],
    colors: [
      { name: "زيتي عسكري", hex: "#4b5320" },
      { name: "أسود فحمي", hex: "#1f2937" },
      { name: "كاكي صحراوي", hex: "#c3b091" },
    ],
    images: [
      "https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=800&auto=format&fit=crop&q=80",
    ],
    isFeatured: false,
    isNew: true,
    sku: "PNT-CRG-04",
  },
  {
    id: 105,
    name: "دريس كاجوال طويل بحزام خصر - ناعم ومريح",
    slug: "casual-cotton-long-dress",
    description: "فستان نسائي كاجوال طويل ومحتشم بخامة بوبلين قطن خفيفة وباردة على الجسم، مع أكمام قابلة للثني وحزام خصر متناسق يمنح مظهراً راقياً ومريحاً للخروج النهاري.",
    fabricDetails: "قطن بوبلين ناعم 100% لا يشف ومقاوم لحرارة الصيف",
    price: 950,
    salePrice: 750,
    stock: 12,
    categoryId: 5,
    categoryName: "ملابس نسائية وكاجوال",
    sizes: ["S", "M", "L", "XL", "2XL"],
    colors: [
      { name: "أخضر زمردي", hex: "#065f46" },
      { name: "وردي ناعم", hex: "#f472b6" },
      { name: "أزرق نيلي", hex: "#1e3a8a" },
    ],
    images: [
      "https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?w=800&auto=format&fit=crop&q=80",
    ],
    isFeatured: true,
    isNew: true,
    sku: "DRS-WMS-05",
  },
  {
    id: 106,
    name: "بليزر كاجوال إيطالي سليم فيت",
    slug: "casual-slim-fit-blazer",
    description: "بليزر كاجوال عصري يمكن ارتداؤه فوق تيشيرت أو قميص، تفصيل إيطالي مبطن جزئياً ليمنحك خفة الحركة والأناقة في المقابلات والمناسبات والعمل.",
    fabricDetails: "مزيج قطن ولكرا خفيف يمنح مرونة وأناقة فائقة",
    price: 1350,
    salePrice: 1090,
    stock: 9,
    categoryId: 6,
    categoryName: "بليزرات وجواكت شياكة",
    sizes: ["48", "50", "52", "54", "56"],
    colors: [
      { name: "كحلي رويال", hex: "#1e3a8a" },
      { name: "رمادي غامق", hex: "#374151" },
      { name: "هافان جملي", hex: "#92400e" },
    ],
    images: [
      "https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=800&auto=format&fit=crop&q=80",
    ],
    isFeatured: true,
    isNew: false,
    sku: "BLZ-SLM-06",
  },
  {
    id: 107,
    name: "سويت بانتس قطني مريح بجيوب سوستة",
    slug: "comfort-cotton-sweatpants",
    description: "سويت بانتس مريح برباط خصر مطاطي متين وجيوب جانبية مزودة بسوستة لحفظ الهاتف والمحفظة بأمان أثناء الحركة وممارسة الرياضة أو المشاوير اليومية.",
    fabricDetails: "قطن ميلتون مصري مطاطي 95% قطن 5% ليكرا",
    price: 490,
    salePrice: 390,
    stock: 30,
    categoryId: 4,
    categoryName: "بناطيل وسويت بانتس",
    sizes: ["M", "L", "XL", "2XL"],
    colors: [
      { name: "أسود", hex: "#111827" },
      { name: "رمادي ميلانج", hex: "#6b7280" },
      { name: "أزرق كحلي", hex: "#1e293b" },
    ],
    images: [
      "https://images.unsplash.com/photo-1552902865-b72c031ac5ea?w=800&auto=format&fit=crop&q=80",
    ],
    isFeatured: false,
    isNew: true,
    sku: "PNT-SWT-07",
  },
  {
    id: 108,
    name: "سويت شيرت كرو نك مطبوع - ديزاين عربي أصيل",
    slug: "crewneck-arabic-typography-sweatshirt",
    description: "سويت شيرت رقبة دائرية كرو نك بطباعة حرارية عالية الدقة لعبارات وخطوط عربية أصيلة تدوم طويلاً دون تشقق.",
    fabricDetails: "قطن مصري ناعم مبطن دافئ",
    price: 650,
    salePrice: 530,
    stock: 16,
    categoryId: 2,
    categoryName: "هوديز وسويت شيرت",
    sizes: ["S", "M", "L", "XL", "2XL"],
    colors: [
      { name: "أبيض كريمي", hex: "#f9fafb" },
      { name: "أسود مطفي", hex: "#18181b" },
    ],
    images: [
      "https://images.unsplash.com/photo-1578587018452-892bacefd3f2?w=800&auto=format&fit=crop&q=80",
    ],
    isFeatured: false,
    isNew: false,
  },
  {
    id: 109,
    name: "شنطة كروس كلاسيك جلد طبيعي - MODANIL Signature",
    slug: "classic-leather-crossbody-bag",
    description: "شنطة كروس أنيقة وبيد علوية مصنوعة من الجلد الطبيعي الفاخر بتشطيب ناعم وأقفال معدنية باللون الذهبي المطفي المقاوم للصدأ. تتضمن حزام كتف قابل للتعديل وجيب داخلي مبطن بسوستة لحفظ المقتنيات اليومية بأناقة وأمان.",
    fabricDetails: "جلد طبيعي فاخر 100% - بطانة ستان قطني ناعم - إكسسوارات معدنية ذهبية",
    price: 890,
    salePrice: 720,
    stock: 15,
    categoryId: 7,
    categoryName: "إكسسوارات وشنط",
    categorySlug: "accessories",
    sizes: ["مقاس موحد"],
    colors: [
      { name: "أسود ملكي", hex: "#111827" },
      { name: "هافان جملي", hex: "#92400e" },
      { name: "عنابي مارون", hex: "#5b1924" },
    ],
    images: [
      "https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1590874103328-eac38a683ce7?w=800&auto=format&fit=crop&q=80",
    ],
    isFeatured: true,
    isNew: true,
    sku: "BAG-CRS-09",
    hasSizeGuide: false,
    badgeText: "إكسسوار حصري ✨",
  },
  {
    id: 110,
    name: "طقم مساكات وتوك شعر ستان حريري كوري (3 قطع)",
    slug: "korean-silk-hair-clips-set",
    description: "مجموعة أنيقة مكونة من 3 قطع من توك ومساكات الشعر المصنوعة من قماش الستان الحريري اللامع والمصممة خصيصاً لتثبيت الشعر بلطف دون شد أو تقصف. ألوان هادئة كلاسيكية تناسب جميع أوقات اليوم والمناسبات.",
    fabricDetails: "ستان حريري ناعم 100% مع مشبك داخلي مرن ومتين",
    price: 240,
    salePrice: 190,
    stock: 25,
    categoryId: 7,
    categoryName: "إكسسوارات وشنط",
    categorySlug: "accessories",
    sizes: ["مقاس موحد"],
    colors: [
      { name: "وردي لؤلؤي", hex: "#f472b6" },
      { name: "شامبين ذهبي", hex: "#fde68a" },
      { name: "أسود كلاسيك", hex: "#111827" },
    ],
    images: [
      "https://images.unsplash.com/photo-1606760227091-3dd870d97f1d?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=800&auto=format&fit=crop&q=80",
    ],
    isFeatured: true,
    isNew: true,
    sku: "ACC-CLP-10",
    hasSizeGuide: false,
    badgeText: "إكسسوار حصري ✨",
  },
];

export const INITIAL_PRODUCTS: ProductItem[] = RAW_INITIAL_PRODUCTS.map((p) => {
  const variants = buildProductVariants(p.id, p.sku || `SKU-${p.id}`, p.sizes, p.colors, p.salePrice || p.price);
  return {
    ...p,
    variants,
    stock: variants.reduce((sum, v) => sum + v.stock, 0),
  };
});

export const INITIAL_ORDERS: OrderItem[] = [
  {
    id: 1001,
    orderNumber: "EG-2026-8941",
    customerName: "أحمد مصطفى الديب",
    customerPhone: "01012458971",
    alternatePhone: "01145896321",
    governorate: "القاهرة",
    city: "مدينة نصر",
    address: "شارع الطيران، متفرع من عباس العقاد، عمارة 24، الدور الثالث، شقة 6",
    notes: "يرجى الاتصال قبل الوصول بنصف ساعة",
    paymentMethod: "cod",
    paymentStatus: "pending",
    orderStatus: "new",
    items: [
      {
        productId: 101,
        name: "تيشيرت أوفر سايز بيزك - قطن مصري فاخر",
        size: "XL",
        color: "أسود ملكي",
        price: 380,
        quantity: 2,
        image: "https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=800&auto=format&fit=crop&q=80",
      },
      {
        productId: 104,
        name: "بنطلون كارجو عملي بجيوب جانبية متعددة",
        size: "34",
        color: "زيتي عسكري",
        price: 490,
        quantity: 1,
        image: "https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=800&auto=format&fit=crop&q=80",
      },
    ],
    subtotal: 1250,
    shippingFee: 45,
    discount: 50,
    couponCode: "WELCOME50",
    total: 1245,
    createdAt: "2026-09-09T14:30:00.000Z",
  },
  {
    id: 1002,
    orderNumber: "EG-2026-8942",
    customerName: "سارة الشريف",
    customerPhone: "01289654123",
    governorate: "الإسكندرية",
    city: "سموحة",
    address: "أبراج الصيادلة، شارع فوزي معاذ، برج رقم 2، شقة 14",
    notes: "تم التحويل على إنستاباي بنجاح",
    paymentMethod: "instapay",
    paymentStatus: "paid",
    orderStatus: "processing",
    items: [
      {
        productId: 105,
        name: "دريس كاجوال طويل بحزام خصر - ناعم ومريح",
        size: "M",
        color: "أخضر زمردي",
        price: 750,
        quantity: 1,
        image: "https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=800&auto=format&fit=crop&q=80",
      },
    ],
    subtotal: 750,
    shippingFee: 55,
    discount: 0,
    total: 805,
    createdAt: "2026-09-08T19:15:00.000Z",
  },
  {
    id: 1003,
    orderNumber: "EG-2026-8943",
    customerName: "محمود عبد العزيز قاسم",
    customerPhone: "01156987412",
    governorate: "الجيزة",
    city: "الشيخ زايد",
    address: "كمبوند بيفرلي هيلز، المرحلة الثانية، فيلا 18",
    notes: "",
    paymentMethod: "cod",
    paymentStatus: "paid",
    orderStatus: "delivered",
    items: [
      {
        productId: 102,
        name: "هودي ميلتون ثقيل مبطن كابيشو - كايرو إديشن",
        size: "L",
        color: "كحلي داكن",
        price: 690,
        quantity: 1,
        image: "https://images.unsplash.com/photo-1556905055-8f358a7a47b2?w=800&auto=format&fit=crop&q=80",
      },
      {
        productId: 106,
        name: "بليزر كاجوال إيطالي سليم فيت",
        size: "52",
        color: "رمادي غامق",
        price: 1090,
        quantity: 1,
        image: "https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=800&auto=format&fit=crop&q=80",
      },
    ],
    subtotal: 1780,
    shippingFee: 0, // Free shipping threshold applied!
    discount: 0,
    total: 1780,
    trackingNumber: "BOSTA-EG-998822",
    createdAt: "2026-09-06T11:00:00.000Z",
  },
  {
    id: 1004,
    orderNumber: "EG-2026-8944",
    customerName: "طارق النجار",
    customerPhone: "01099887766",
    governorate: "الدقهلية (المنصورة)",
    city: "حي الجامعة",
    address: "شارع جيهان، أمام بوابة جامعة المنصورة، عمارة البرج، الدور الخامس",
    notes: "الدفع فودافون كاش",
    paymentMethod: "vodafone_cash",
    paymentStatus: "paid",
    orderStatus: "shipped",
    items: [
      {
        productId: 103,
        name: "قميص كتان طبيعي صيفي خفيف",
        size: "XL",
        color: "أبيض صيفي",
        price: 520,
        quantity: 2,
        image: "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=800&auto=format&fit=crop&q=80",
      },
    ],
    subtotal: 1040,
    shippingFee: 55,
    discount: 100,
    couponCode: "EGYPT100",
    total: 995,
    trackingNumber: "Mylerz-EG-54210",
    createdAt: "2026-09-07T16:20:00.000Z",
  },
];

export const INITIAL_COUPONS: CouponItem[] = [
  {
    id: 1,
    code: "WELCOME50",
    discountType: "fixed",
    discountValue: 50,
    minOrderValue: 400,
    usageLimit: 500,
    usedCount: 34,
    isActive: true,
  },
  {
    id: 2,
    code: "EGYPT20",
    discountType: "percentage",
    discountValue: 20,
    minOrderValue: 600,
    usageLimit: 200,
    usedCount: 18,
    isActive: true,
  },
  {
    id: 3,
    code: "SUMMER15",
    discountType: "percentage",
    discountValue: 15,
    minOrderValue: 350,
    usageLimit: 100,
    usedCount: 12,
    isActive: true,
  },
];

import { STORE_DEFAULTS } from "@/lib/egypt-constants";

export const INITIAL_SETTINGS: StoreSettingsItem = {
  storeName: STORE_DEFAULTS.storeName,
  phone: STORE_DEFAULTS.phone,
  whatsapp: STORE_DEFAULTS.whatsapp,
  supportEmail: STORE_DEFAULTS.supportEmail,
  instapayHandle: STORE_DEFAULTS.instapayHandle,
  instapayPhone: STORE_DEFAULTS.phone,
  vodafoneCashPhone: STORE_DEFAULTS.vodafoneCashPhone,
  freeShippingThreshold: STORE_DEFAULTS.freeShippingThreshold,
  bannerNotice: STORE_DEFAULTS.bannerNotice,
  isBannerActive: true,
  isAcceptingOrders: true,
  isMaintenanceMode: false,
  estimatedDeliveryDays: STORE_DEFAULTS.estimatedDeliveryDays,
  enabledPaymentMethods: ["cod", "instapay", "vodafone_cash", "card"],
  orderClosedMessage: STORE_DEFAULTS.orderClosedMessage,
  maintenanceMessage: STORE_DEFAULTS.maintenanceMessage,
  // Branding & Assets
  logoUrl: STORE_DEFAULTS.logoUrl,
  storeTagline: STORE_DEFAULTS.storeTagline,
  storeDescription: STORE_DEFAULTS.storeDescription,
  // Location & Social
  physicalAddress: STORE_DEFAULTS.physicalAddress,
  facebookUrl: STORE_DEFAULTS.facebookUrl,
  instagramUrl: STORE_DEFAULTS.instagramUrl,
  tiktokUrl: STORE_DEFAULTS.tiktokUrl,
  // Hero CMS
  heroBadge: STORE_DEFAULTS.heroBadge,
  heroTitle: STORE_DEFAULTS.heroTitle,
  heroSubtitle: STORE_DEFAULTS.heroSubtitle,
  heroBgImage: STORE_DEFAULTS.heroBgImage,
  heroPrimaryBtnText: STORE_DEFAULTS.heroPrimaryBtnText,
  heroPrimaryBtnLink: STORE_DEFAULTS.heroPrimaryBtnLink,
  // Special Promo Banner
  isPromoBannerActive: STORE_DEFAULTS.isPromoBannerActive,
  promoBadge: STORE_DEFAULTS.promoBadge,
  promoTitle: STORE_DEFAULTS.promoTitle,
  promoDescription: STORE_DEFAULTS.promoDescription,
  promoCouponCode: STORE_DEFAULTS.promoCouponCode,
  // SEO Defaults
  seoTitle: STORE_DEFAULTS.seoTitle,
  seoDescription: STORE_DEFAULTS.seoDescription,
  seoKeywords: STORE_DEFAULTS.seoKeywords,
};
